# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build and Push

on:
  push:
    branches: [ "files" ]
    
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install and Build
        run: |
          yarn
          yarn run build --mode cdn
  
      - name: Commit dist
        run: |
          git checkout --orphan dist
          mv dist ../
          rm -rf ./*
          mv ../dist/* ./
          git config --local user.email 'l1040186796@gmail.com'
          git config --local user.name 'AkashiCoin'
          git add .
          git commit -m "chore(dist): upload dist"

      - name: Upload dist files
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: web-dist
          repository: AkashiCoin/imgbed
          force: true